name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Trigger build on version tags (e.g., v1.0.1)
  workflow_dispatch:  # Allow manual execution

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history to properly detect tags

    - name: Get Latest Tag and Generate New Version
      id: versioning
      run: |
        git fetch --tags
        LATEST_TAG=$(git tag --sort=-v:refname | head -n 1)
        if [ -z "$LATEST_TAG" ]; then
          NEW_TAG="v1.0.0"
        else
          NEW_TAG=$(echo "$LATEST_TAG" | awk -F. -v OFS=. '{ $NF += 1 ; print }')
        fi
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        echo "Generated new version: $NEW_TAG"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t harishkumarthesde/content-moderator:latest -f Dockerfile .
        docker tag harishkumarthesde/content-moderator:latest harishkumarthesde/content-moderator:${{ env.NEW_TAG }}

    - name: Push Docker Image
      run: |
        docker push harishkumarthesde/content-moderator:latest
        docker push harishkumarthesde/content-moderator:${{ env.NEW_TAG }}

    - name: Push New Git Tag (Only if Pushed to Main)
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.email "harishkumar56278@gmail.com"
        git config --global user.name "harish-nika"
        git tag -a ${{ env.NEW_TAG }} -m "Release ${{ env.NEW_TAG }}"
        git push --force origin ${{ env.NEW_TAG }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use a personal access token (PAT)
